#!/bin/bash

### All constants goes here

### All functions should goes here

function print_usage()
{
   echo "Usage: image-stitcher.sh [build | run | plot]"
} 


function build_image_stitcher()
{
   echo "Building project ..."
   mvn clean package

   if [ $? != "0" ]; then
      echo "Build failed."
      exit $?
   else
      echo "Build successful"
   fi
}

function plot_data()
{
   outputFilePath=$1
   if [[ -z "$outputFilePath" ]]; then
      echo "Please specify file path to read data points"
      echo "Usage: image-stitcher.sh plot [output part file generated by the program]"
      echo "Example: ./image-stitcher.sh plot /home/hadoop/output/part-r-00000"
      exit 0     
   fi

   mvn dependency:build-classpath -Dmdep.outputFile=classpath.tmp > /dev/null
   java -cp target/image-stitcher-1.0.jar:`cat classpath.tmp` neu.nctracer.data.plot.Client $outputFilePath true false

   if [ $? != "0" ]; then
      echo "Error while plotting scatter plot"
      rm classpath.tmp
      exit 0
   else
      rm classpath.tmp
   fi
}

function run_image_stitch
{
   inputPath=$1
   outputPath=$2

   if [ -z "$inputPath" ] || [ -z "$outputPath" ]; then
      echo "Need 2 arguments to run the program ..."
      echo "Usage: image-stitcher.sh run [input directory path] [output directory to be created]"
      echo "Example: ./image-stitcher.sh run /home/hadoop/input /home/hadoop/output"
      exit 0
   fi

   hadoop jar target/image-stitcher-1.0.jar $inputPath $outputPath
   
   if [ $? != "0" ]; then
      echo "Execution failed. Something went wrong. Please check logs for details."
      exit 0
   fi
}

### Main starts here

if [ $# == 0 ]; then
   # no arguments found
   print_usage
   exit 0
fi

case $1 in
   build)
     build_image_stitcher
     ;;

   plot)
     plot_data $2
     ;;
    
   run)
     run_image_stitch $2 $3
     ;;

   *)
     echo "Invalid command found ..."
     print_usage
     exit 0
esac

